# Generated by Django 5.1.1 on 2024-09-04 22:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serv_name', models.CharField(default='Nombre del Servicio', max_length=64)),
                ('description', models.CharField(default='Descripcion del Servicio', max_length=255)),
                ('type', models.CharField(choices=[('APP', 'Aplicacion'), ('APPM', 'Aplicacion movil'), ('SERV', 'Servidores')], max_length=64)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Task', max_length=64)),
                ('description', models.CharField(default='Task description', max_length=128)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, default=datetime.date.today)),
                ('progress', models.FloatField(default=0.0)),
                ('status', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
